### ISSUE TITLE
API

### ISSUE THREAD

**Issue by aziliak** [ZacharyHampton/OnlyFansExpiredSubFollower#1]
Hey Zachary,

Where did you find information regarding the OnlyFans API?

I may modify this code so that it can do additional things like send custom messages (not sure if this already does it or not) as well as other things.

Thanks.

**Comment by ZacharyHampton** [comment]
@aziliak Hello, it does not send custom messages, it only follows previous subs whom are expired. To get endpoints to use, the way I did it was just logging requests via Chrome DevTools. I would do the same if I were you. There is no publicly available documentation for OF I believe, not so sure, I didn't use it.

**Comment by aziliak** [comment]
Gotcha.  Thanks for your advice!!!
