### ISSUE TITLE
Code does not run when converted to javascript, any reason for that?

### ISSUE THREAD

**Issue by Shashank003** [ZacharyHampton/OnlyFansExpiredSubFollower#2]
I converted the code to javascript, and double checked the header value being generated. It is the same for both the code bases. However, any requests being made to the Onlyfans server seem to fail with 400 error, and are logging me out. Could you help me understand why its happening?

**Comment by SneakyOvis** [comment]
Is the original python code working?

Also, you can start with something more simple:
https://github.com/SneakyOvis/onlyfans-dynamic-rules/tree/main/python

Once you get that working, add the required functions to the Account class.
Finally, translate all this into JavaScript.

**Comment by Shashank003** [comment]
Yes, the original code is working in python. I double checked the sign, their values generated are the same when I hard code in the time values. However the requests are failing, when being made from the browser itself with javascript. I will share my code in the next comment:

**Comment by Shashank003** [comment]
Here is the link to my repo: https://github.com/Shashank003/ExpiredFanFollower 

In it everytime I make the call, the server logs me out with a 400 error. I am running the code in my browser console itself.

**Comment by SneakyOvis** [comment]
Can you log headers? And paste output.
```
headers = createSignedHeaders(url, referrer)
console.log(headers)
```

**Comment by Shashank003** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/20090498/216341427-a8996c68-0610-4441-9277-fe74ea4945fb.png)

The above is for the url = 'https://onlyfans.com/api2/v2/subscriptions/count/all' and referer as shown in the output. Maybe we can see if for the same time, you are getting the same output for the same user_id. I am fetching the dynamic rules from 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json', which is working in python

**Comment by SneakyOvis** [comment]
Text, please... Have mercy ;)

**Comment by Shashank003** [comment]
{
    "sign": "6820:3322ffc1e828c0b798910202711cec04f5ee760c:95b:63d81407",
    "time": "1675345985179",
    "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "x-bc": "751a971d7d3eb8c7e2581c0a62a557ca74015ad3",
    "user-id": "262976705",
    "referer": "https://onlyfans.com/my/subscribers/expired",
    "authority": "onlyfans.com",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-ch-ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
}

**Comment by Shashank003** [comment]
What do you think? Is there an issue with my api call, or signed header generation?

**Comment by SneakyOvis** [comment]
I'll check that later, busy for now :(

**Comment by Shashank003** [comment]
No issues. We can discuss later. I would also be willing to pay you to make this work if you are interested, it's really important for me.

**Comment by SneakyOvis** [comment]
Well, well, what's that? :)
```
async function createSignedHeaders(url, referer)
[...]
headers = createSignedHeaders(url, referrer)
```
Do you know what 'async' means in JS?

BTW
There's an email address in my profile, just read it ;)

**Comment by Shashank003** [comment]
The function needs to be not asynchronous? I'll change it to a normal function. Sorry, I'm a bit new to javascript. Also, do I need to copy the cookie values to the header, or since I'm calling it from the browser, I dont need to set cookies anywhere. Also, I tried to reach you through email, could you type it out. I appended the string you wanted me to append for the email and added @gmail.com, but it still didnt work :/.

Also, could you please tell me what to change to fix it?

Update: I fixed it. The api call seems to be working for now at least. Please give me your email, so we can communicate if I need you or collaborate in the future. Thanks you've been really helpful :).

**Comment by SneakyOvis** [comment]
```
async function createSignedHeaders(url, referer)
[...]
headers = await createSignedHeaders(url, referrer)
```
Cookies are set by the browser. And many other headers.

The email address is there, sorry man, it's very easy.
