### ISSUE TITLE
Handling onlyfans rate limits

### ISSUE THREAD

**Issue by Shashank003** [ZacharyHampton/OnlyFansExpiredSubFollower#3]
What will happen if we hit the maximum number of users you can follow in a day on onlyfans? What error message will come at that point, when we try to follow a user, and how to handle that error?

**Comment by ZacharyHampton** [comment]
If you hit a rate limit, it takes a break & retries (bad solution, but works).  When you hit your max for the day, the program stops.

**Comment by Shashank003** [comment]
What about running a counter, resetting it to 0 everyday, and running it uptil 95 follows? When it reaches 95 follows for the day, it just gives an alert.

**Comment by ZacharyHampton** [comment]
> What about running a counter, resetting it to 0 everyday, and running it uptil 95 follows? When it reaches 95 follows for the day, it just gives an alert.

You can create a fork and do that if you'd like, however the current solution works just fine.
